/* CONRES.H          NOTE: This is a MASTER copy - DO NOT CHANGE THIS FILE */
/* File updates must be implemented by using the REDITOR Compile option on */
/* C:\TOONCES\CONFLICT\CONRESUS.RS                                         */
/* Copyright (c) 1989 Lotus Development Corporation.  All Rights Reserved. */


#if !defined(CONRES_H)
#define CONRES_H


#define MSGCONFLICTBOTH 0

#define MSGCONFLICTFILE1 1

#define MSGCONFLICTFILE2 2

#define MSGCONFLICTNEITHER 3

#define MSGCONFLICTADD 4

#define MSGCONFLICTDELETE 5

#define MSGCONFLICTQUERY 6

#define MSGCONFLICTQUERY2 7

#define MSGCONFLICTABORT 8

#define MSGCONFLICTABORT1 9

#define MSGLOG0 10

#define MSGLOG1 11

#define MSGLOG2 12

#define FKEYCONFLICTHELP 13

#define FKEYCONFLICTBOTH 14

#define FKEYCONFLICTFILE1 15

#define FKEYCONFLICTFILE2 16

#define FKEYCONFLICTADD 17

#define FKEYCONFLICTDELETE 18

#define FKEYCONFLICTNEITHER 19

#define FKEYCONFLICTCANCEL 20

#define FKEYCONFLICTOK 21

#define MSG_BADDATE 256

#define MSG_BADTIME 257

#define MSG_BADNUMBER 258

#define MSG_BADCHECKBOX 259

#define MSG_BADCDFSYNTAX 260

#define MSG_CONRES_COMPLETED 261

#define MSG_CONRES_DELETED 262

#define MSG_CONRES_SYNCCOPYFAIL 263

#define MSG_CONRES_SRC_EQ_TAR 264

#define MSG_CONRES_BAD_LOG 265

#define MSG_CONRES_TRUNCATED_DATA 266


#endif
