/* SCCS info:   Module crt.h  Version 1.1  Date 11/09/93  Time 15:17:37 */

/* $Header:   T:/HH/INCLUDE/VCS/CRT.H_V   1.1   15 Oct 1992 10:49:10   KIM  $ */
/****************************************************************
 *
 *	Copyright(c) 1990  Lotus Development Corporation
 *	All Rights Reserved
 *
 ****************************************************************/
/*
 * $Log:   T:/HH/INCLUDE/VCS/CRT.H_V  $ 
 * 
 *    Rev 1.1   15 Oct 1992 10:49:10   KIM
 * * * * SERVER DISK CRASH RECOVERY * * *
 *  1) The VCS directory was restored with Build 18 backup tape.
 *  2) This revision is to update files to Build 19.
 *  3) HELP.H has post-Build 19 changes.
 * 
 *    Rev 1.0   03 Dec 1991 20:14:36   DAVID
 * Initial revision.
 *
 */



#define NORMAL		0
#define INVERSE 	1  
#define WINDOW		2  

