/* SCCS info:   Module hmtop.h  Version 1.1  Date 11/09/93  Time 15:19:45 */

/* $Header:   T:/HH/INCLUDE/VCS/HMTOP.H_V   1.1   15 Oct 1992 10:50:44   KIM  $ */
/* $Log:   T:/HH/INCLUDE/VCS/HMTOP.H_V  $
 * 
 *    Rev 1.1   15 Oct 1992 10:50:44   KIM
 * * * * SERVER DISK CRASH RECOVERY * * *
 *  1) The VCS directory was restored with Build 18 backup tape.
 *  2) This revision is to update files to Build 19.
 *  3) HELP.H has post-Build 19 changes.
 * 
 *    Rev 1.0   05 Aug 1992 22:07:28   DAVID
 * Initial revision.
 */


#define TOP_INTRO	0
#define SYS_MEM		1

