/* SCCS info:   Module htop.h  Version 1.1  Date 11/09/93  Time 15:19:55 */

/* $Header:   T:/HH/INCLUDE/VCS/HTOP.H_V   1.2   15 Oct 1992 10:50:48   KIM  $ */
/* $Log:   T:/HH/INCLUDE/VCS/HTOP.H_V  $
 * 
 *    Rev 1.2   15 Oct 1992 10:50:48   KIM
 * * * * SERVER DISK CRASH RECOVERY * * *
 *  1) The VCS directory was restored with Build 18 backup tape.
 *  2) This revision is to update files to Build 19.
 *  3) HELP.H has post-Build 19 changes.
 * 
 *    Rev 1.1   05 Aug 1992 22:07:28   DAVID
 * 
 *    Rev 1.0   05 Aug 1992 22:03:28   DAVID
 * Initial revision.
 */

#define TOP_LANG	0
#define TOP_COUN	1
#define TOP_INFO	2
#define TOP_INTRO	3
#define SYS_PLUG	4
#define SYS_BAT		5
#define SYS_MEM		6

