/* SCCS info:   Module printer.h  Version 1.1  Date 11/09/93  Time 15:23:57 */

/* $Header:   T:/HH/INCLUDE/VCS/PRINTER.H_V   1.1   15 Oct 1992 10:52:06   KIM  $ */
/****************************************************************************
 *
 *      Copyright(c) 1992  Lotus Development Corporation
 *      All Rights Reserved
 *
 ***************************************************************************/

/*
 * $Log:   T:/HH/INCLUDE/VCS/PRINTER.H_V  $
 * 
 *    Rev 1.1   15 Oct 1992 10:52:06   KIM
 * * * * SERVER DISK CRASH RECOVERY * * *
 *  1) The VCS directory was restored with Build 18 backup tape.
 *  2) This revision is to update files to Build 19.
 *  3) HELP.H has post-Build 19 changes.
 * 
 *    Rev 1.0   16 Sep 1992 18:27:12   HOMI
 * Initial revision.
*/



/****************************************************************************
 TEXT PRINTER ATTRIBUTE
****************************************************************************/

#define     ATB_B_ON             1        /* bold on */ 
#define     ATB_B_OFF            2        /* bold off */
#define     ATB_I_ON             3        /* italics on */
#define     ATB_I_OFF            4        /* italics off */
#define     ATB_U_ON             5        /* underline on */
#define     ATB_U_OFF            6        /* underline off */
#define     ATB_BI_ON            7        /* bold + italics on */
#define     ATB_BI_OFF           8        /* bold + italics off */
#define     ATB_BU_ON            9        /* bold + underline on */
#define     ATB_BU_OFF           10       /* bold + underline off */
#define     ATB_BIU_ON           11       /* bold + underline + italics on */
#define     ATB_BIU_OFF          12       /* bold + underline + italics off */
#define     ATB_IU_ON            13       /* italics + underline on */
#define     ATB_IU_OFF           14       /* italics + underline off */

