/* SCCS info:   Module vimlcl.h  Version 1.1  Date 11/09/93  Time 15:26:22 */

/* $Header:   T:/HH/INCLUDE/VCS/VIMLCL.H_V   1.2   29 Oct 1992 10:00:22   ROGER  $ */
/**************************************************************************
 *
 * Name:        VIMLCL.H
 * Date:        Tuesday October 27, 1992
 * Abstract:    Contains the local bindings for the cc:Mail version of
 *              VIM (the VIM Requestor).
 *
 * ------------------------------------------------------------------------
 *                   Copyright 1992 Lotus Development Corp.
 *                           All rights reserved.
 **************************************************************************
 *
 * $Log:   T:/HH/INCLUDE/VCS/VIMLCL.H_V  $
 * 
 *    Rev 1.2   29 Oct 1992 10:00:22   ROGER
 * Removed the lines of code that were commented out.  See the revision
 * history for the last set of changes made.
 * 
 *    Rev 1.1   28 Oct 1992 11:37:28   ROGER
 * Moved the VIM_MSGTYPE_LEN, VIM_ITEMTYPE_LEN, and MCAP_SUBJECT_LEN to the
 * MCAP.H include file.
 *
 **************************************************************************/

#define VIM_VOID            void
#define VIM_FAR             _far
#define VIMAPIENTRY         _cdecl
#define VIM_PTR

